### ISSUE TITLE
Require prefix for all use, speed up regex matching

### ISSUE THREAD

**Issue by KayOhtie** [pelican-plugins/pelimoji#2]
Requiring a default prefix `ce` (custom emoji) may help speed up regex matching times, this will need some testing for times. The override option will still exist but may fall back on a default.

Current default: `:emoji_name:`

New default: `:ce-emoji_name:`

Since this is a breaking change I'd like input on it before I start to push it.

**Comment by justinmayer** [comment]
Speaking for me personally, I'd probably prioritize friendly syntax over speed, since my sites aren't so large that generation speed is a problem. That said, I know folks with large sites would probably appreciate the performance optimization. As long as there is a way to choose one or the other, then folks would be free to choose whether they care more about (1) friendly syntax or (2) speed. What do you think?

**Comment by KayOhtie** [comment]
I'm in agreement after thinking about it more. ~~I think I may adjust the prefix option to basically be the alternative. Something like, one can go without a prefix but if you have a very large number of emojis -- like say using all of [Mutant Standard](https://mutant.tech/) like I have -- a prefix may be preferable to speed up HTML compilation but isn't required.~~ Actually relying on only prefix still presents the flaw of "what if that isn't a valid emoji" being turned into an oddball character or unpredictable actual emoji displayed. I think this could be revisited later, but for now it's not an issue, and site compilation isn't super frequent.
