### ISSUE TITLE
Remove unmaintained Glue dependency

### ISSUE THREAD

**Issue by justinmayer** [pelican-plugins/pelimoji#6]
Unfortunately, the [Glue](https://github.com/jorgebastida/glue) dependency has not seen an update in over three years, with many issues outstanding and unaddressed. Most importantly, Glue has [pinned Jinja2](https://github.com/jorgebastida/glue/blob/master/setup.py#L7) to a narrow set of acceptable versions (`Jinja2>=2.7,<2.10`), making it impossible to install Glue alongside the current version of Pelican, since Pelican currently requires `Jinja2 >= 2.11`.

One potential solution would be to loosen the restriction on Pelican’s side, accepting `Jinja2 >= 2.09`. That *might* work, but it would only be a temporary bandaid, since the next Jinja2 update containing significant changes would bring us right back to the same problem.

Other solutions include:

* find an alternative project to provide the functionality that Glue currently provides

* convince @jorgebastida to release a new version of Glue with updated Jinja2 requirements, preferably by specifying only a minimum version and eliminating the maximum version constraint

* fork Glue, fix it, and re-publish to PyPI under a different name

@Ceralor / @jorgebastida: What do you think?

**Comment by KayOhtie** [comment]
I'm happy to look into alternative solutions. It took a while to find Glue, which I settled on due to _primarily_ being pure Python (aside the development headers for the OS sometimes, unless Pillow installed from the OS packages). I liked the customizability of using Jinja2 for the CSS file itself too. I think forking it to update for Pelimoji specifically or to at least keep updated, or for @jorgebastida to update the requirements (hopefully little work on their part) would be ideal as opposed to finding something else.

**Comment by justinmayer** [comment]
Understandable. I don't want to bother @jorgebastida any more than I already have, so I forked the repository and removed the upper constraint on Jinja2: https://github.com/justinmayer/glue/commit/71c504de1544f9aa87d103508f231644d2505b21

Then I updated Pelimoji's Glue dependency to point to the forked repository: 0bdda44

With this change, there shouldn't be any need to loosen requirements on Pelican's side. Glue is still woefully in need of maintenance, but at least with this change, Glue will install and seems to continue to perform the function that Pelimoji requires of it. 😊

**Comment by justinmayer** [comment]
Actually, this strategy won't work. I tried publishing Pelimoji to PyPI, but the process failed because PyPI does not support non-packaged dependencies (such as, in this case, references to Git repositories). So unfortunately publishing Pelimoji to PyPI is blocked until this situation is sorted out. 😞

**Comment by KayOhtie** [comment]
Could submit your changes as a PR to the original repo but I know that requires some work.

Alternatively, the licensing allows for us to embed it directly as long as we keep the notice, and could by extension properly, as a library include, build the emoji map rather than using an exec. I'm up for making that work happen!

Also examining some examples on DIYing sprite sheets and removing the dependency entirely to directly requiring PIL and assorted things instead.

**Comment by justinmayer** [comment]
> Could submit your changes as a PR to the original repo but I know that requires some work.

The reason I hesitate to pursue that route isn't because it requires some work, but rather because there hasn't been any Glue project activity for over three years, and thus I don't have any confidence that a PR to Glue would be merged.

The other options seem much more promising. Thank you for being so willing to explore them! 😁

**Comment by KayOhtie** [comment]
Happy to explore! I understand that concern, which was mine as well, though
the account does appear to be pretty active on Github. I'll look into
integrating it or taking from it what's needed. I'm not sure if I need to
do anything unique to make Pelican play nice with an actively-developed
plugin like that I'm working on?

**Comment by justinmayer** [comment]
> I'm not sure if I need to do anything unique to make Pelican play nice with an actively-developed plugin like that I'm working on?

Not that I can think of, but then again I'm not exactly sure what you mean here. Perhaps if you elaborate?

**Comment by justinmayer** [comment]
@Ceralor removed the Glue dependency in #8, and I just published the first version of Pelimoji to PyPI.

@Ceralor: Many thanks for everything you did to make this happen. Bravo! 🌟
